pub mod background;
pub mod catalog;
pub mod color;
pub mod debayer;
pub mod fits;
pub mod ingest;
pub mod register;
pub mod skycat;
pub mod solve;
pub mod stack;
pub mod stars;
pub mod stretch;
pub mod wcs;

pub use background::{fit as fit_background, subtract as subtract_background, BackgroundOpts};
pub use catalog::{scan_dir, scan_file, Group, Kind, Scan, Scanned};
pub use color::{is_narrowband, Calibration, ColorOpts, Reference};
pub use debayer::{to_rgb_half, Rgb};
pub use fits::{Header, Image, Value};
pub use ingest::{ingest, FrameRecord};
pub use register::{register, RegisterOpts, Transform};
pub use stars::{detect, DetectOpts, Star, StarField};
pub use stretch::{auto_stf, auto_stf_channels, mtf, Stf};
pub use wcs::Wcs;
